= How to write a RESTful Web API: a declarative approach
:toc: left
:toclevels: 2
:sectnums:
:sectlevels: 3
:includedir:

Welcome to this comprehensive guide to creating
https://en.wikipedia.org/wiki/Representational_state_transfer[REST]ful services.

[CAUTION]
--
This page is a work-in-progress. Consider ALPHA status. It was last
updated on {docdatetime}.

However, it is considered in a state worthy of
publication and you should still be able to learn a lot from it.

If you want to provide feedback, head over to the project https://github.com/juxt/rest/discussions[discussions] page.
--

== Introduction

////
Make this guide a gentle sympathetic approach - 'Beware of the Curse of Knowledge' (https://www.bti360.com/what-ive-learned-in-45-years-in-the-software-industry/)
////

So you want to provide a RESTful Web API?

If you're happy with a first-cut quick-and-dirty get-the-job-done
implementation, then perhaps this guide isn't for you.

If you're new to programming, then this probably isn't the best guide to follow either
(although writing a Web API isn't a _bad_ programming project to improve your
skills).

If you want to write a 'proper' RESTful Web API, one that can be run in a
production environment, work well, be solid and maintainable, then *this is the
guide for you*.

Along the way, you'll learn about what it really means to be a RESTful Web API, and much more, including:

* The difference between resources and representations
* Content negotiation--how resources can be mapped to multiple representations, and when you need to pick one
* Methods--what you have to do for each method you support
* Status codes--which status codes you should return in your responses, and when
* Conditional requests--how certain requests should proceed only if certain tests pass (called preconditions)
* Ranges--when representations are large, how to serve only the fragments that are actually needed
* Caching--how to make the use of web caches to help your API to scale
* Authorization--how to restrict access to your service to authorized parties

This guide is meant to be followed one step after another. At each step, feel
free to stop and perhaps dive into some of the references we'll provide. If
nothing else, you'll learn a lot!

=== Some words on the 'declarative approach'

One of the six 'architectural constraints' of REST is the 'Uniform
interface'. Your API should be broken up into one or more *resources*.

In REST, each resource should behave more-or-less the same way, following a
consistent set of rules. Although these rules are numerous and fairly tricky to
implement in places, the good news is that you shouldn't have to follow these
steps for _each_ resource you create.

The code you write as a result of following this guide should work for _all_
your resources. Ultimately, that should mean a lot less code to write and
maintain!

The way we will achieve such code _economy_ is by using a declarative
approach. Where possible, your code should behave according to the details of
individual resources provided as input argument.

In our view, all code should either be implementing a compiler or an interpretter.

TIP: Another benefit of this approach is that having separated the code from the
data declarations that drive it, you can store that data inside a
_database_. Hey, you could even use our https://opencrux.com[Crux] database!

=== Clojure?

We've chosen to use https://clojure.org/[Clojure] for the example code in this
guide. Clojure is concise, and lends itself well to data-driven coding.

That said, it doesn't actually matter which programming language you choose to
implement your web API in. The example code is small and easily translated to
other programming languages.

=== Library support

If you do want to follow this guide using Clojure, you'll be able to make use of
https://github.com/juxt/spin[a support library] of 'helper' functions,
called *Spin*, that much of the example code utilises.

Spin also brings in some additional niche libraries:

* https://github.com/juxt/pick[pick] -- when you have more than one 'representation' for a resource to select, you can ask pick to choose for you. Pick is based on the same algorithm used by the Apache HTTP Server.

* https://github.com/juxt/reap[reap] -- when Spin and Pick need to encode and decode certain strings (e.g. inside HTTP headers), they call out to corresponding functions in Reap. This reduces the amount of code, and protects against certain security attacks based on sending malformed inputs.

=== Is this a web framework?

No.

[quote,Stuart Halloway,Twitter]
____
Library composition outperforms framework callbacks in the long run. The long run typically begins on day two.
____

None of the support libraries used here accept 'callbacks', and that's why we
don't call the composition a 'web framework'.

The major downside of our approach *more work for _you_ to do*. There is no
magical web framework to orchestrate everything for you.

The payback is that you retain control of your implementation. Ultimately, _you_
make the decisions and can choose to deviate from this guide when
appropriate. You spend more time wrangling your own problems and less time
wrangling the web framework you've adopted.

This also leads to you reaching a deeper _understanding_ of your own web API
service, what it does and how to change it to meet new requirements. You'll also
learn more about the parts of the web that web frameworks hide from you.

_For many, this payback is well worth the extra effort._

Good luck, be brave, take small assured steps, one step at a time.

=== Is there a complete solution somewhere?

If you want a complete solution to study, you can find one
https://github.com/juxt/spin/blob/master/examples/demo/src/demo.clj[here].

=== How to get involved?

If you want to provide feedback, share ideas or otherwise contribute, please
head over to our project https://github.com/juxt/rest/discussions[discussions]
page.

== Preliminaries

=== Clojure setup

With Clojure's Ring library, we can handle a web request with a
function. <<ring-handler>> illustrates a simple function that takes the web
request and returns a web response.

[[ring-handler]]
.A simple Ring handler
====
[source,clojure]
----
(fn [req] <1>
  {:status 200 :body "OK"} <2>
)
----
<1> `req` is a Clojure map, containing details of the incoming web request
<2> This map is the value returned from the function. It contains details of the outgoing web response.
====

NOTE: The decision whether to adop the classic synchronous single-arity Ring
handler functions, or asynchronous 3-arity Ring handler functions, is out of
scope for this guide. You may use either.

== Request checks

[[check-service-available]]
=== Is the service available?

[quote,,503 Service Unavailable -- Section 6.6.4 RFC 7231]
____
The 503 (Service Unavailable) status code indicates that the server
is currently unable to handle the request due to a temporary overload
or scheduled maintenance
____

. Check that your service is not overwhelmed with requests.

. If it is, throw an exception. Otherwise, go to <<check-implemented-method,the next
step>>.

NOTE: How you can tell this is beyond the scope of this guide. It might be a feature
of the web listener you are working with. Or you might want to build something
that signals that new web requests should temporarily suspended. If you don't
know, just skip this section, it's optional.

====
In Clojure, when throwing an exception, embed the Ring response as exception data. This might include a `Retry-After` header and the time to wait, in seconds.

[source,clojure]
----
(throw
  (ex-info "Service unavailable"
  {::response <1>
   {:status 503
    :headers {"retry-after" "120"} <2>
    :body "Service Unavailable\r\n"}}))
----
<1> Embed the Ring response as exception data.
<2> Add a `Retry-After` header.

Your whole handler should be wrapped in a
https://clojuredocs.org/clojure.core/try[try/catch] block.

The catch block should catch the exception, extract the Ring response, and
return it to the Ring adapter of th web server you are running.
====

==== References

* 503 Service Unavailable -- https://tools.ietf.org/html/rfc7231#section-6.6.4[Section 6.6.4, RFC 7231]
* Retry-After -- https://tools.ietf.org/html/rfc7231#section-7.1.3[Section 7.1.3, RFC 7231]

[[check-implemented-method]]
=== Check method is implemented

[quote,,501 Not Implemented -- Section 6.6.2 RFC 7231]
____
The 501 (Not Implemented) status code indicates that the server does
not support the functionality required to fulfill the request.
____

The next step is to check whether the request method is one your implementation
recognises.

. Check if the *request method* is recognised.

.. If so, go to <<locate-resource,the next step>>.

.. If not, throw an exception containing a `501 (Not Implemented)` error response.

====
In Clojure, throw an exception like this:

[source,clojure]
----
(throw
  (ex-info
   "Method not implemented"
   {::response
    {:status 501
     :body "Not Implemented\r\n"}}))
----

The spin library offers a helper function that checks the request method is one of a set of known common HTTP methods, and if necessary, throws the exception as described:

[source,clojure]
----
(spin/check-method-not-implemented! request)
----
====

==== References

* 501 Not Implemented -- https://tools.ietf.org/html/rfc7231#section-6.6.2[Section 6.6.2, RFC 7231]

[[locate-resource]]
=== Locate the resource

[quote,Resources -- Section 2 RFC 7231]
____
The target of an HTTP request is called a "resource".
____

. Use the URL of the request to lookup or otherwise locate the resource object (which can be null).

.. Hold this data structure as a variable, and go to <<the next step>>.

Typically, a resource object will include the following:

* The resource's identifier (the URI) or, at least, its path
* Which methods are allowed on the resource?
* Current representations
* Which ranges, if any, are acceptable?
* Authorization rules - who is allowed to access this resource and how?
* The allowed types of submitted representations
* Anything else that is useful

[quote,Roy Fielding,Architectural Styles and the Design of Network-based Software Architectures]
____
An origin server maintains a mapping from resource identifiers to the set of representations corresponding to each resource
____

////
The set of *request method* tokens might very well depend on details in the
request. For example, a resource might allow a POST but only if the request is
_authorized_ to do so. So you can make use of any information in the request,
not just the URL, to determine the set of *request method* tokens
allowed. Moreover, if some attribute or attributes of a resource are referred to
in making such a decision, or affect the processing of request methods (at the
minimum, the *request method* in the current request), then these should be
included in the *resource* too.
////

TIP: Try to avoid using the *request method* when locating a resource--a
*resource* value should encompass _all_ its methods.

====
In Clojure, you might choose to use a map as a *resource*.

For example, here is a map that corresponds to a *resource*. It tells us that
the resource allows the methods GET, POST, PUT and DELETE.

[source,clojure]
----
{::spin/path "/orders"
 ::spin/methods #{:get :post :put :delete}}
----

You can use a router to locate the *resource*. See
link:examples/reitit/src/reitit_example.clj[] for an example using the
https://github.com/metosin/reitit[Reitit] router.

Alternatively, we can resolve the resource in any other way that's
appropriate. For example, since resources can be modelled as data values, they
can be stored in a key/value database. Locating a resource is simply a matter of
looking it up using the URL as the key.
====

=== Authenticate the request

. Add to the request, any roles, credentials or entitlements that can be
acquired. Use information in the resource found in <<locate-resource>> to
determine the *authentication scheme* and/or *protection space*.

.. This usually involved inspecting the request's `Authorization` header and/or other
headers, frequently `Cookie` headers.

=== Authorize the request

. Update the resource object according to the authenticated request's roles,
credentials or other entitlements.

.. If the resource cannot be accessed without credentials, and if none have been
supplied (or ones that have been supplied are invalid) throw an exception that
contains a `401 (Unauthorized)` error response. This response may include a
`WWW-Authenticate` header to indicate to the user agent that it should resend
the request with credentials.

.. If the request does contain valid authenticated credentials, but they are
insufficient to provide access to the resource given the request's method, throw
an exception that contains a `403 (Forbidden)` error response, or a `404 (Not
Found)` error response if you want to hide the existence of the unauthorized
resource to the user.

=== Validate the request with respect to the resource

. If the request is not valid, throw an exception containing a 400 response.

This step might also involve validating parameters, for example, to meet the expectations of a set of OpenAPI parameter declarations.

[[check-method-allowed]]
=== Check method allowed

. Check the request method against the methods allowed by the resource.

.. If the request method isn't allowed, throw an exception containing a '405 (Method Not Allowed)' error response and an `Allow` header.

=== Record the time

. Get the system time and store it in a variable.

=== Establish the current representations

. Using the resource, determine the current representations and store in a
variable.

=== Negotiate the most acceptable current representation

For the given *resource*, determine the content negotiation strategy and follow
one of the sections below (although it is permissable to use a hybrid or
combination of strategies).

TIP: If in doubt, use <<proactive-content-negotiation,proactive content negotiation>>, which is by far the most
commonly strategy.

* <<proactive-content-negotiation>>
* <<reactive-content-negotiation>>

[[proactive-content-negotiation]]
==== Proactive Content Negotiation

1. Determine the set of available current representations for the resource.

2. If step 1. yields no representations, and the method is a GET or HEAD, throw
an exception containing a `404 (Not Found)` error response.

3. Select the most acceptable representation from this set, using the preferences contained in the request.
.. If there is no such acceptable representation, and the method is a GET
or HEAD, throw an exception containing a `406 (Not Acceptable)` error
response. Construct a body containing links to each unacceptable representation
from step 1.
.. Otherwise store the most acceptable current representation in a variable called `selected-representation` to move to the next step.

****
The https://github.com/juxt/pick[pick] library is written expressly for the
purpose of proactive (server-driven) content negotiation.

See https://github.com/juxt/pick for further details.
****

[[reactive-content-negotiation]]
==== Reactive Content Negotiation

1. Determine the set of available *representations* for the resource.

2. If step 1. yields no representations, return a 404 error response. Go to <<error-response>>.

3. Optionally, filter this set using the preferences contained in the request.

4. If step 3. yields a single representation, then use this as the representation and _move on to the next section_.

5. If step 3. yields multiple *representations*, respond with a 300 response and construct a body containing links to each representation in this filtered set.

=== Performing the acion

You should now perform the action associated with the request method.

. Go to the section that matches the request method:

. <<get>>
. <<post>>
. <<put>>
. <<delete>>
. <<options>>

[[get]]
== The GET (and HEAD) methods

NOTE: The procedure for HEAD is identical to that of GET, with the exception
that we do not produce any body in the response.

. Evaluate preconditions

. Optionally, if there is a `Range` header, parse it.

.. If the units of the range header isn't supported by the resource, throw an exception with a `400 Bad Request` error response.

.. If there is an `If-Range` header, process it (TODO)

. Get the payload of the selected representation

[[post]]
== The POST method

[[put]]
== The PUT method

[quote,,PUT]
____
The PUT method requests that the state of the target resource be
created or replaced with the state defined by the representation
enclosed in the request message payload.
____

. Read the representation enclosed in the request message payload

.. Check the request has a `Content-Length` header. If not, throw an exception
containing a `411 Length Required` error response.


[[delete]]
== The DELETE method

[[options]]
== The OPTIONS method


[appendix]
== Supplementary steps

The procedures in this section are linked to from the main content.

[[evaluate-preconditions]]
=== Evaluate preconditions

For any request method that involves the selection or modification of a
representation (e.g. GET, POST, PUT, DELETE), a set of preconditions are
evaluated.

Here's the procedure:

. If the request contains an `If-Match` header field value, and

.. If the value is `*` and the resource has no mapped representations, return a
`412 (Precondition Failed)` error response.

.. If none of the entity-tags in `If-Match` strongly match the entity tag of the
selected representation, return a `412 (Precondition Failed)` error response.

. If the request does not have an `If-Match` header, but contains the header
`If-Unmodified-Since`, and

.. If the `last-modified` value of the representation metadata of the selected
representation is _after_ the date in the `If-Unmodified-Since` header, return a
`412 (Precondition Failed)` error response.

. If the request contains an `If-None-Match` header field value,

.. If the `If-None-Match` header field value contains an entity-tag which weakly
matches the `etag` value of the representation metadata of the selected
representation, OR if the `If-None-Match` header value is `*` and there is at
least one current representation for the resource,

... If the request method is a GET or HEAD, return a `304 (Not Modified)`
response,

... Otherwise, return a `412 (Precondition Failed)` error response.

. Otherwise, if the request does not have an `If-None-Match` header field value,

.. If the request method is GET or HEAD, and the request has a
`If-Modified-Since` header field value, unless the `last-modified` value of the
representation metadata of the selected representation is after the value of the
`If-Modified-Since` header field value, return a `304 (Not Modified)` response.

====
Spin has a utility function you can call with the request, resource and
representation metadata of the selected representation.

The function will evaluate the preconditions using the header field values in
the request and the representation metadata of the selected representation,
throwing an exception at any point one of the preconditions fails.

[source,clojure]
----
(spin/evaluate-preconditions! request resource selected-representation-metadata)
----
====

==== References

See RFC 7233 Section 6



=== Error

If you want to send an error response, you should decide whether to send a body
in the response. This might contain information about the error and explain to
the user-agent (or human) how to avoid the error in future.

. Perform content negotiation to establish the best representation to send.

. Add the *representation metadata* to the response headers, and stream the
*representation data* as the the *body* of the response.



[bibliography]
== References

* [[[cowboy]]] https://github.com/ninenines/cowboy[Cowboy] is a callback-based web framework in Erlang, sharing similar goals of full conformance with HTTP standards.

* [[[Fielding-2000]]] R. Fielding https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm[Architectural Styles and
the Design of Network-based Software Architectures]. 2000

* [[[liberator]]] https://github.com/clojure-liberator/liberator[Liberator] is a Clojure library by Philip Meier _(et. al.)_ based on Alan Dean's https://github.com/basho/webmachine/blob/master/docs/http-headers-status-v3.png[activity diagram].

* [[[RFC7230]]] R. Fielding, J. Rescheke, _(et. al.)_ https://tools.ietf.org/html/rfc7230[RFC 7230. Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing]. Internet Engineering Task Force (IETF). 2014.

* [[[RFC7231]]] R. Fielding, J. Rescheke, _(et. al.)_ https://tools.ietf.org/html/rfc7231[RFC 7231. Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content]. Internet Engineering Task Force (IETF). 2014.

* [[[RFC7232]]] R. Fielding, J. Rescheke, _(et. al.)_ https://tools.ietf.org/html/rfc7232[RFC 7232. Hypertext Transfer Protocol (HTTP/1.1): Conditional Requests]. Internet Engineering Task Force (IETF). 2014.

* [[[RFC7233]]] R. Fielding, J. Rescheke, _(et. al.)_ https://tools.ietf.org/html/rfc7233[RFC 7233. Hypertext Transfer Protocol (HTTP/1.1): Range Requests]. Internet Engineering Task Force (IETF). 2014.

* [[[RFC7234]]] R. Fielding, J. Rescheke, _(et. al.)_ https://tools.ietf.org/html/rfc7234[RFC 7234. Hypertext Transfer Protocol (HTTP/1.1): Caching]. Internet Engineering Task Force (IETF). 2014.

* [[[RFC7235]]] R. Fielding, J. Rescheke, _(et. al.)_ https://tools.ietf.org/html/rfc7235[RFC 7235. Hypertext Transfer Protocol (HTTP/1.1): Authentication]. Internet Engineering Task Force (IETF). 2014.

* [[[Webmachine]]] https://github.com/basho/webmachine[webmachine] is based on an https://github.com/basho/webmachine/blob/master/docs/http-headers-status-v3.png[activity diagram], first created by Alan Dean.

* [[[yada]]] https://github.com/juxt/yada[yada] is a JUXT project with similar aims but technically a framework requiring callback functions.


////
,
https://tools.ietf.org/html/rfc7231[7231],
https://tools.ietf.org/html/rfc7232[7232],
https://tools.ietf.org/html/rfc7233[7233],
https://tools.ietf.org/html/rfc7234[7234] and
https://tools.ietf.org/html/rfc7235[7235].
////

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// eval: (local-set-key (kbd "<M-up>") 'outline-move-subtree-up)
// eval: (local-set-key (kbd "<M-down>") 'outline-move-subtree-down)
// End:
